[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "example_pipeline"
code_location_name = "example_pipeline"

[tool.pytest_env]
AWS_BUCKET = "bucket"
