name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Test with pytest
      run: |
        export SOURCE_FILENAME=in/test.csv
        pip install -e .
        pip install pytest pytest-cov
        pytest --doctest-modules --junitxml=junit/test-results.xml --cov=example_pipeline --cov-report=xml --cov-report=html example_pipeline_test

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '30 80'

  ruff:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Lint with Ruff
      run: |
        pip install ruff
        ruff check --output-format=github .


  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag codekarma/dagster-ecs-example:latest
