name: Docker Image CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag codekarma/dagster-ecs-example:latest
